<?php
const CANTRIP_SLOT_SPELL_NAME = "[CANTRIP]";
const CANTRIP_SLOT_SPELL_CATALOG_ID = 1665;
const CANTRIP_SLOT_SPELL_LEVEL = 10;
const CANTRIP_SLOT_SPELL_TYPE = 8;
const CANTRIP_SLOT_RACIAL_RESTRICTION = 1;
?>