<?php

const EMPTY_SLOT_SPELL_NAME = "[NONE]";
const EMPTY_SLOT_SPELL_CATALOG_ID = 1664;
const EMPTY_SLOT_SPELL_LEVEL = 10;
const EMPTY_SLOT_SPELL_TYPE = 7;
const EMPTY_SLOT_RACIAL_RESTRICTION = 1;

?>