<?php

const AKLYS = 1;	
const ATLATL = 2;	
const BATTLE_AXE = 3;	
const HAND_AXE = 4;	
const BASILARD = 5;	
const BAGH_NAKH = 6;	
const BARDICHE = 7;	
const BEC_DE_CORBIN = 8;	
const BILL_GUISARME = 9;	
const BLACKJACK = 10;	
const BLOWGUN = 11;	
const BO_STICK = 12;	
const BOLA = 13;	
const LONG_COMPOSITE_BOW = 14;	
const SHORT_COMPOSITE_BOW = 15;	
const LONG_BOW = 16;	
const SHORT_BOW = 17;	
const ELVEN_CRAFT_BOW = 18;	
const BOOMERANG = 19;	
const CALTROP = 20;	
const DWARVEN_CLAYMORE = 21;	
const CLUB = 22;	
const CHAKRAM = 23;	
const HAND_CROSSBOW = 24;	
const LIGHT_CROSSBOW = 25;	
const HEAVY_CROSSBOW = 26;	
const GREAT_CROSSBOW = 27;	
const DWARVEN_WAR_CLUB = 28;	
const DAGGER = 29;	
const DART = 30;	
const DART_THRUSTER = 31;	
const DOKYU = 32;	
const DWARVEN_BUCKLER_AXE = 33;	
const DWARVEN_DOUBLE_SPEAR = 34;	
const DWARVEN_WAR_PIKE = 35;	
const ELVEN_COURT_BLADE = 36;	
const ELVEN_LIGHTBLADE = 37;	
const ELVEN_THIN_BLADE = 38;	
const FAUCHARD = 39;	
const FORK = 40;	
const FOOTMANS_FLAIL = 41;	
const HORSEMANS_FLAIL = 42;	
const MILITARY_FORK = 43;	
const GARROT = 44;	
const GLAIVE = 45;	
const GLAIVE_GUISARME = 46;	
const GNOME_TORTOISE_BLADE = 47;	
const GUISARME = 48;	
const GUISARME_VOULGE = 49;	
const HALBERD = 50;	
const HALFLING_SKIP_ROCK = 51;	
const HAMMER = 52;	
const GREAT_HAMMER = 53;	
const LUCERN_HAMMER = 54;	
const DWARVEN_THROWING_HAMMER = 55;	
const HARPOON = 56;	
const FAUCHARD_HOOK = 57;	
const IRON_FAN = 58;	
const JAVELIN = 59;	
const JUNG_MEH = 60;	
const JO_STICK = 61;	
const KAPAR = 62;	
const KATANA = 63;	
const KATAR = 64;	
const KNIFE = 65;	
const KUNAI = 66;	
const LIGHT_LANCE = 67;	
const MEDIUM_LANCE = 68;	
const HEAVY_LANCE = 69;	
const LASSO = 70;	
const FOOTMANS_MACE = 71;	
const HORSEMANS_MACE = 72;	
const MAN_CATCHER = 73;	
const MAN_CATCHER_WITH_HOOK = 74;	
const MAUL = 75;	
const MORNING_STAR = 76;	
const DOUBLE_BALLED_MORNING_STAR = 77;	
const NAGINATA = 78;	
const NUNCHAKU = 79;	
const PARTISAN = 80;	
const MILITARY_FOOTMANS_PICK = 81;	
const MILITARY_HORSEMANS_PICK = 82;	
const AWL_PIKE = 83;	
const RANSEUR = 84;	
const SAI = 85;	
const SABRE = 86;	
const SAP = 87;	
const SCIMITAR = 88;	
const SCYTHE = 89;	
const SHURIKEN = 90;	
const SLING = 91;	
const SPEAR = 92;	
const SPETUM = 93;	
const BASTARD_SWORD = 94;	
const BROAD_SWORD = 95;	
const FALCHION_SWORD = 96;	
const FLAMBERGE_SWORD = 97;	
const MARINERS_SWORD = 98;	
const PIERCER_SWORD = 99;	
const SHORT_SWORD = 100;	
const TWO_HANDED_SWORD = 101;	
const STAFF = 102;	
const STAFF_SLING = 103;	
const THREE_SECTIONED_STAFF = 104;	
const THROWING_KNIFE = 105;	
const HOOKED_THROWING_NET = 106;	
const WEIGHTED_THROWING_NET = 107;	
const TONFA = 108;	
const TLACOCHTLI = 109;	
const TRIDENT = 110;	
const VOULGE = 111;	
const UCHI_NE = 112;	
const WAKIZASHI = 113;	
const WHIP = 114;	
const YAWARA = 115;	
const KHOPESH_SWORD = 116;	
const LONG_SWORD = 117;	
const FIST = 118;

function getWeaponDescriptionFromProficiencyId($weapon_proficiency_id) {
    switch($weapon_proficiency_id) {
        case AKLYS: return 'Aklys';	
        case ATLATL: return 'Atlatl';	
        case BATTLE_AXE: return 'Battle Axe';	
        case HAND_AXE: return 'Hand Axe';	
        case BASILARD: return 'Basilard';	
        case BAGH_NAKH: return 'Bagh Nakh';	
        case BARDICHE: return 'Bardiche';	
        case BEC_DE_CORBIN: return 'Bec de Corbin';	
        case BILL_GUISARME: return 'Bill-Guisarme';	
        case BLACKJACK: return 'Blackjack';	
        case BLOWGUN: return 'Blowgun';	
        case BO_STICK: return 'Bo Stick';	
        case BOLA: return 'Bola';	
        case LONG_COMPOSITE_BOW: return 'Long Composite Bow';
        case SHORT_COMPOSITE_BOW: return 'Short Composite Bow';	
        case LONG_BOW: return 'Long Bow';	
        case SHORT_BOW: return 'Short Bow';	
        case ELVEN_CRAFT_BOW: return 'Elven Craft Bow';	
        case BOOMERANG: return 'Boomerang';	
        case CALTROP: return 'Caltrop';	
        case DWARVEN_CLAYMORE: return 'Dwarven Claymore';	
        case CLUB: return 'Club';	
        case CHAKRAM: return 'Chakram';	
        case HAND_CROSSBOW: return 'Hand Crossbow';	
        case LIGHT_CROSSBOW: return 'Light Crossbow';	
        case HEAVY_CROSSBOW: return 'Heavy Crossbow';	
        case GREAT_CROSSBOW: return 'Great Crossbow';	
        case DWARVEN_WAR_CLUB: return 'Dwarven War Club';	
        case DAGGER: return 'Dagger';	
        case DART: return 'Dart';	
        case DART_THRUSTER: return 'Dart Thruster';	
        case DOKYU: return 'Dokyu';	
        case DWARVEN_BUCKLER_AXE: return 'Dwarven Buckler Axe';
        case DWARVEN_DOUBLE_SPEAR: return 'Dwarven Double Spear';
        case DWARVEN_WAR_PIKE: return 'Dwarven War Pike';	
        case ELVEN_COURT_BLADE: return 'Elven Court Blade';
        case ELVEN_LIGHTBLADE: return 'Elven Lightblade';	
        case ELVEN_THIN_BLADE: return 'Elven Thin Blade';	
        case FAUCHARD: return 'Fauchard';	
        case FORK: return 'Fork';	
        case FOOTMANS_FLAIL: return 'Footmans Flail';	
        case HORSEMANS_FLAIL: return 'Horsemans Flail';	
        case MILITARY_FORK: return 'Military Fork';	
        case GARROT: return 'Garrot';	
        case GLAIVE: return 'Glaive';	
        case GLAIVE_GUISARME: return 'Glaive-Guisarme';	
        case GNOME_TORTOISE_BLADE: return 'Gnome Tortoise Blade';	
        case GUISARME: return 'Guisarme';	
        case GUISARME_VOULGE: return 'Guisarme-Voulge';	
        case HALBERD: return 'Halberd';	
        case HALFLING_SKIP_ROCK: return 'Halfling Skip Rock';
        case HAMMER: return 'Hammer';	
        case GREAT_HAMMER: return 'Great Hammer';	
        case LUCERN_HAMMER: return 'Lucern Hammer';	
        case DWARVEN_THROWING_HAMMER: return 'Dwarven Throwing Hammer';	
        case HARPOON: return 'Harpoon';	
        case FAUCHARD_HOOK: return 'Fauchard Hook';	
        case IRON_FAN: return 'Iron Fan';	
        case JAVELIN: return 'Javelin';	
        case JUNG_MEH: return 'Jung Meh';	
        case JO_STICK: return 'Jo Stick';	
        case KAPAR: return 'Kapar';	
        case KATANA: return 'Katana';	
        case KATAR: return 'Katar';	
        case KNIFE: return 'Knife';	
        case KUNAI: return 'Kunai';	
        case LIGHT_LANCE: return 'Light Lance';	
        case MEDIUM_LANCE: return 'Medium Lance';	
        case HEAVY_LANCE: return 'Heavy Lance';	
        case LASSO: return 'Lasso';	
        case FOOTMANS_MACE: return 'Footmans Mace';	
        case HORSEMANS_MACE: return 'Horsemans Mace';	
        case MAN_CATCHER: return 'Man-Catcher';	
        case MAN_CATCHER_WITH_HOOK: return 'Man-Catcher with Hook';
        case MAUL: return 'Maul';	
        case MORNING_STAR: return 'Morning Star';	
        case DOUBLE_BALLED_MORNING_STAR: return 'Double-balled Morning Star';
        case NAGINATA: return 'Naginata';	
        case NUNCHAKU: return 'Nunchaku';	
        case PARTISAN: return 'Partisan';	
        case MILITARY_FOOTMANS_PICK: return 'Military Footmans Pick';
        case MILITARY_HORSEMANS_PICK: return 'Military Horsemans Pick';
        case AWL_PIKE: return 'Awl Pike';	
        case RANSEUR: return 'Ranseur';	
        case SAI: return 'Sai';	
        case SABRE: return 'Sabre';	
        case SAP: return 'Sap';	
        case SCIMITAR: return 'Scimitar';	
        case SCYTHE: return 'Scythe';	
        case SHURIKEN: return 'Shuriken';	
        case SLING: return 'Sling';	
        case SPEAR: return 'Spear';	
        case SPETUM: return 'Spetum';	
        case BASTARD_SWORD: return 'Bastard Sword';	
        case BROAD_SWORD: return 'Broad Sword';	
        case FALCHION_SWORD: return 'Falchion Sword';	
        case FLAMBERGE_SWORD: return 'Flamberge Sword';	
        case MARINERS_SWORD: return 'Mariners Sword';	
        case PIERCER_SWORD: return 'Piercer Sword';	
        case SHORT_SWORD: return 'Short Sword';	
        case TWO_HANDED_SWORD: return 'Two-Handed Sword';	
        case STAFF: return 'Staff';	
        case STAFF_SLING: return 'Staff Sling';	
        case THREE_SECTIONED_STAFF: return 'Three Sectioned Staff';
        case THROWING_KNIFE: return 'Throwing Knife';	
        case HOOKED_THROWING_NET: return 'Hooked Throwing Net';
        case WEIGHTED_THROWING_NET: return 'Weighted Throwing Net';
        case TONFA: return 'Tonfa';	
        case TLACOCHTLI: return 'Tlacochtli';	
        case TRIDENT: return 'Trident';	
        case VOULGE: return 'Voulge';	
        case UCHI_NE: return 'Uchi-Ne';	
        case WAKIZASHI: return 'Wakizashi';	
        case WHIP: return 'Whip';	
        case YAWARA: return 'Yawara';	
        case KHOPESH_SWORD: return 'Khopesh Sword';	
        case LONG_SWORD: return 'Long Sword';	
        case FIST: return 'Fist';	
        default : return "UNKNOWN";
    }
}
?>