<?php
declare(strict_types=1);

require_once __DIR__ . '/../dbio/constants/characterAttributes.php';
require_once __DIR__ . '/../dbio/constants/characterRaces.php';

const MALE = 'M';
const FEMALE = 'F';

const MIN = 'n';
const MAX = 'x';

$attributes_min_max = [];

function getMinForMale($attributes_min_max, $attribute, $race_id) {
    return $attributes_min_max[$attribute][$race_id][MALE][MIN];
}

function getMaxForMale($attributes_min_max, $attribute, $race_id) {
    return $attributes_min_max[$attribute][$race_id][MALE][MAX];
}

function getMinForFemale($attributes_min_max, $attribute, $race_id) {
    return $attributes_min_max[$attribute][$race_id][FEMALE][MIN];
}

function getMaxForFemale($attributes_min_max, $attribute, $race_id) {
    return $attributes_min_max[$attribute][$race_id][FEMALE][MAX];
}

// Strength
$attributes_min_max[CHARACTER_STRENGTH] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_DARK_ELF] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_DARK_ELF][MALE] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_DARK_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_DARK_ELF][MALE][MIN] = 5;
$attributes_min_max[CHARACTER_STRENGTH][RACE_DARK_ELF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_STRENGTH][RACE_DARK_ELF][FEMALE][MIN] = 5;
$attributes_min_max[CHARACTER_STRENGTH][RACE_DARK_ELF][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_STRENGTH][RACE_HIGH_ELF] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_HIGH_ELF][MALE] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_HIGH_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_HIGH_ELF][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_STRENGTH][RACE_HIGH_ELF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_STRENGTH][RACE_HIGH_ELF][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_STRENGTH][RACE_HIGH_ELF][FEMALE][MAX] = 16;

$attributes_min_max[CHARACTER_STRENGTH][RACE_GRAY_DWARF] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_GRAY_DWARF][MALE] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_GRAY_DWARF][FEMALE] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_GRAY_DWARF][MALE][MIN] = 8;
$attributes_min_max[CHARACTER_STRENGTH][RACE_GRAY_DWARF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_STRENGTH][RACE_GRAY_DWARF][FEMALE][MIN] = 8;
$attributes_min_max[CHARACTER_STRENGTH][RACE_GRAY_DWARF][FEMALE][MAX] = 17;

$attributes_min_max[CHARACTER_STRENGTH][RACE_GRAY_ELF] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_GRAY_ELF][MALE] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_GRAY_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_GRAY_ELF][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_STRENGTH][RACE_GRAY_ELF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_STRENGTH][RACE_GRAY_ELF][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_STRENGTH][RACE_GRAY_ELF][FEMALE][MAX] = 16;

$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_DROW] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_DROW][MALE] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_DROW][FEMALE] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_DROW][MALE][MIN] = 5;
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_DROW][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_DROW][FEMALE][MIN] = 5;
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_DROW][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_ELF] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_ELF][MALE] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_ELF][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_ELF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_ELF][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_ELF][FEMALE][MAX] = 17;

$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_ORC] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_ORC][MALE] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_ORC][FEMALE] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_ORC][MALE][MIN] = 6;
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_ORC][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_ORC][FEMALE][MIN] = 6;
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_ORC][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_STRENGTH][RACE_HALFLING] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALFLING][MALE] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALFLING][FEMALE] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALFLING][MALE][MIN] = 6;
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALFLING][MALE][MAX] = 17;
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALFLING][FEMALE][MIN] = 6;
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALFLING][FEMALE][MAX] = 14;

$attributes_min_max[CHARACTER_STRENGTH][RACE_HIGH_ELF] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_HIGH_ELF][MALE] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_HIGH_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_HIGH_ELF][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_STRENGTH][RACE_HIGH_ELF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_STRENGTH][RACE_HIGH_ELF][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_STRENGTH][RACE_HIGH_ELF][FEMALE][MAX] = 16;

$attributes_min_max[CHARACTER_STRENGTH][RACE_HILL_DWARF] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_HILL_DWARF][MALE] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_HILL_DWARF][FEMALE] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_HILL_DWARF][MALE][MIN] = 8;
$attributes_min_max[CHARACTER_STRENGTH][RACE_HILL_DWARF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_STRENGTH][RACE_HILL_DWARF][FEMALE][MIN] = 8;
$attributes_min_max[CHARACTER_STRENGTH][RACE_HILL_DWARF][FEMALE][MAX] = 17;

$attributes_min_max[CHARACTER_STRENGTH][RACE_HUMAN] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_HUMAN][MALE] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_HUMAN][FEMALE] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_HUMAN][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_STRENGTH][RACE_HUMAN][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_STRENGTH][RACE_HUMAN][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_STRENGTH][RACE_HUMAN][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_STRENGTH][RACE_MOUNTAIN_DWARF] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_MOUNTAIN_DWARF][MALE] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_MOUNTAIN_DWARF][FEMALE] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_MOUNTAIN_DWARF][MALE][MIN] = 8;
$attributes_min_max[CHARACTER_STRENGTH][RACE_MOUNTAIN_DWARF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_STRENGTH][RACE_MOUNTAIN_DWARF][FEMALE][MIN] = 8;
$attributes_min_max[CHARACTER_STRENGTH][RACE_MOUNTAIN_DWARF][FEMALE][MAX] = 17;

$attributes_min_max[CHARACTER_STRENGTH][RACE_OOMPA_LLOOMPA] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_OOMPA_LLOOMPA][MALE] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_OOMPA_LLOOMPA][FEMALE] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_OOMPA_LLOOMPA][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_STRENGTH][RACE_OOMPA_LLOOMPA][MALE][MAX] = 16;
$attributes_min_max[CHARACTER_STRENGTH][RACE_OOMPA_LLOOMPA][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_STRENGTH][RACE_OOMPA_LLOOMPA][FEMALE][MAX] = 15;

$attributes_min_max[CHARACTER_STRENGTH][RACE_SURFACE_GNOME] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_SURFACE_GNOME][MALE] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_SURFACE_GNOME][FEMALE] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_SURFACE_GNOME][MALE][MIN] = 6;
$attributes_min_max[CHARACTER_STRENGTH][RACE_SURFACE_GNOME][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_STRENGTH][RACE_SURFACE_GNOME][FEMALE][MIN] = 6;
$attributes_min_max[CHARACTER_STRENGTH][RACE_SURFACE_GNOME][FEMALE][MAX] = 15;

$attributes_min_max[CHARACTER_STRENGTH][RACE_VALLEY_ELF] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_VALLEY_ELF][MALE] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_VALLEY_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_VALLEY_ELF][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_STRENGTH][RACE_VALLEY_ELF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_STRENGTH][RACE_VALLEY_ELF][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_STRENGTH][RACE_VALLEY_ELF][FEMALE][MAX] = 16;

$attributes_min_max[CHARACTER_STRENGTH][RACE_WILD_ELF] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_WILD_ELF][MALE] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_WILD_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_WILD_ELF][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_STRENGTH][RACE_WILD_ELF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_STRENGTH][RACE_WILD_ELF][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_STRENGTH][RACE_WILD_ELF][FEMALE][MAX] = 16;

$attributes_min_max[CHARACTER_STRENGTH][RACE_WOOD_ELF] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_WOOD_ELF][MALE] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_WOOD_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_WOOD_ELF][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_STRENGTH][RACE_WOOD_ELF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_STRENGTH][RACE_WOOD_ELF][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_STRENGTH][RACE_WOOD_ELF][FEMALE][MAX] = 16;

$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_ELF_GRAY] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_ELF_GRAY][MALE] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_ELF_GRAY][FEMALE] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_ELF_GRAY][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_ELF_GRAY][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_ELF_GRAY][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_ELF_GRAY][FEMALE][MAX] = 17;

$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_ELF_VALLEY] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_ELF_VALLEY][MALE] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_ELF_VALLEY][FEMALE] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_ELF_VALLEY][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_ELF_VALLEY][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_ELF_VALLEY][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_ELF_VALLEY][FEMALE][MAX] = 17;

$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_ELF_WILD] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_ELF_WILD][MALE] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_ELF_WILD][FEMALE] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_ELF_WILD][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_ELF_WILD][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_ELF_WILD][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_ELF_WILD][FEMALE][MAX] = 17;

$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_ELF_WOOD] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_ELF_WOOD][MALE] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_ELF_WOOD][FEMALE] = [];
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_ELF_WOOD][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_ELF_WOOD][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_ELF_WOOD][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_STRENGTH][RACE_HALF_ELF_WOOD][FEMALE][MAX] = 17;

// Intelligence
$attributes_min_max[CHARACTER_INTELLIGENCE] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_DARK_ELF] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_DARK_ELF][MALE] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_DARK_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_DARK_ELF][MALE][MIN] = 8;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_DARK_ELF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_DARK_ELF][FEMALE][MIN] = 10;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_DARK_ELF][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HIGH_ELF] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HIGH_ELF][MALE] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HIGH_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HIGH_ELF][MALE][MIN] = 8;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HIGH_ELF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HIGH_ELF][FEMALE][MIN] = 8;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HIGH_ELF][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_GRAY_DWARF] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_GRAY_DWARF][MALE] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_GRAY_DWARF][FEMALE] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_GRAY_DWARF][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_GRAY_DWARF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_GRAY_DWARF][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_GRAY_DWARF][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_GRAY_ELF] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_GRAY_ELF][MALE] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_GRAY_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_GRAY_ELF][MALE][MIN] = 8;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_GRAY_ELF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_GRAY_ELF][FEMALE][MIN] = 8;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_GRAY_ELF][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_DROW] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_DROW][MALE] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_DROW][FEMALE] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_DROW][MALE][MIN] = 8;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_DROW][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_DROW][FEMALE][MIN] = 10;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_DROW][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_ELF] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_ELF][MALE] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_ELF][MALE][MIN] = 4;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_ELF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_ELF][FEMALE][MIN] = 4;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_ELF][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_ORC] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_ORC][MALE] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_ORC][FEMALE] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_ORC][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_ORC][MALE][MAX] = 17;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_ORC][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_ORC][FEMALE][MAX] = 17;

$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALFLING] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALFLING][MALE] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALFLING][FEMALE] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALFLING][MALE][MIN] = 6;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALFLING][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALFLING][FEMALE][MIN] = 6;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALFLING][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HIGH_ELF] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HIGH_ELF][MALE] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HIGH_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HIGH_ELF][MALE][MIN] = 8;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HIGH_ELF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HIGH_ELF][FEMALE][MIN] = 8;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HIGH_ELF][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HILL_DWARF] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HILL_DWARF][MALE] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HILL_DWARF][FEMALE] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HILL_DWARF][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HILL_DWARF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HILL_DWARF][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HILL_DWARF][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HUMAN] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HUMAN][MALE] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HUMAN][FEMALE] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HUMAN][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HUMAN][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HUMAN][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HUMAN][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_MOUNTAIN_DWARF] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_MOUNTAIN_DWARF][MALE] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_MOUNTAIN_DWARF][FEMALE] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_MOUNTAIN_DWARF][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_MOUNTAIN_DWARF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_MOUNTAIN_DWARF][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_MOUNTAIN_DWARF][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_OOMPA_LLOOMPA] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_OOMPA_LLOOMPA][MALE] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_OOMPA_LLOOMPA][FEMALE] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_OOMPA_LLOOMPA][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_OOMPA_LLOOMPA][MALE][MAX] = 17;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_OOMPA_LLOOMPA][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_OOMPA_LLOOMPA][FEMALE][MAX] = 17;

$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_SURFACE_GNOME] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_SURFACE_GNOME][MALE] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_SURFACE_GNOME][FEMALE] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_SURFACE_GNOME][MALE][MIN] = 7;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_SURFACE_GNOME][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_SURFACE_GNOME][FEMALE][MIN] = 7;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_SURFACE_GNOME][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_VALLEY_ELF] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_VALLEY_ELF][MALE] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_VALLEY_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_VALLEY_ELF][MALE][MIN] = 8;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_VALLEY_ELF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_VALLEY_ELF][FEMALE][MIN] = 8;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_VALLEY_ELF][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_WILD_ELF] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_WILD_ELF][MALE] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_WILD_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_WILD_ELF][MALE][MIN] = 8;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_WILD_ELF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_WILD_ELF][FEMALE][MIN] = 8;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_WILD_ELF][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_WOOD_ELF] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_WOOD_ELF][MALE] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_WOOD_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_WOOD_ELF][MALE][MIN] = 8;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_WOOD_ELF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_WOOD_ELF][FEMALE][MIN] = 8;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_WOOD_ELF][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_ELF_GRAY] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_ELF_GRAY][MALE] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_ELF_GRAY][FEMALE] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_ELF_GRAY][MALE][MIN] = 4;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_ELF_GRAY][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_ELF_GRAY][FEMALE][MIN] = 4;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_ELF_GRAY][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_ELF_VALLEY] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_ELF_VALLEY][MALE] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_ELF_VALLEY][FEMALE] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_ELF_VALLEY][MALE][MIN] = 4;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_ELF_VALLEY][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_ELF_VALLEY][FEMALE][MIN] = 4;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_ELF_VALLEY][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_ELF_WILD] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_ELF_WILD][MALE] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_ELF_WILD][FEMALE] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_ELF_WILD][MALE][MIN] = 4;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_ELF_WILD][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_ELF_WILD][FEMALE][MIN] = 4;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_ELF_WILD][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_ELF_WOOD] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_ELF_WOOD][MALE] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_ELF_WOOD][FEMALE] = [];
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_ELF_WOOD][MALE][MIN] = 4;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_ELF_WOOD][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_ELF_WOOD][FEMALE][MIN] = 4;
$attributes_min_max[CHARACTER_INTELLIGENCE][RACE_HALF_ELF_WOOD][FEMALE][MAX] = 18;

// Wisdom
$attributes_min_max[CHARACTER_WISDOM] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_DARK_ELF] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_DARK_ELF][MALE] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_DARK_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_DARK_ELF][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_WISDOM][RACE_DARK_ELF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_WISDOM][RACE_DARK_ELF][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_WISDOM][RACE_DARK_ELF][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_WISDOM][RACE_HIGH_ELF] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_HIGH_ELF][MALE] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_HIGH_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_HIGH_ELF][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_WISDOM][RACE_HIGH_ELF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_WISDOM][RACE_HIGH_ELF][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_WISDOM][RACE_HIGH_ELF][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_WISDOM][RACE_GRAY_DWARF] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_GRAY_DWARF][MALE] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_GRAY_DWARF][FEMALE] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_GRAY_DWARF][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_WISDOM][RACE_GRAY_DWARF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_WISDOM][RACE_GRAY_DWARF][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_WISDOM][RACE_GRAY_DWARF][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_WISDOM][RACE_GRAY_ELF] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_GRAY_ELF][MALE] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_GRAY_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_GRAY_ELF][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_WISDOM][RACE_GRAY_ELF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_WISDOM][RACE_GRAY_ELF][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_WISDOM][RACE_GRAY_ELF][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_DROW] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_DROW][MALE] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_DROW][FEMALE] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_DROW][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_DROW][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_DROW][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_DROW][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_ELF] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_ELF][MALE] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_ELF][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_ELF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_ELF][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_ELF][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_ORC] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_ORC][MALE] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_ORC][FEMALE] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_ORC][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_ORC][MALE][MAX] = 14;
$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_ORC][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_ORC][FEMALE][MAX] = 14;

$attributes_min_max[CHARACTER_WISDOM][RACE_HALFLING] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_HALFLING][MALE] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_HALFLING][FEMALE] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_HALFLING][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_WISDOM][RACE_HALFLING][MALE][MAX] = 17;
$attributes_min_max[CHARACTER_WISDOM][RACE_HALFLING][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_WISDOM][RACE_HALFLING][FEMALE][MAX] = 17;

$attributes_min_max[CHARACTER_WISDOM][RACE_HIGH_ELF] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_HIGH_ELF][MALE] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_HIGH_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_HIGH_ELF][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_WISDOM][RACE_HIGH_ELF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_WISDOM][RACE_HIGH_ELF][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_WISDOM][RACE_HIGH_ELF][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_WISDOM][RACE_HILL_DWARF] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_HILL_DWARF][MALE] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_HILL_DWARF][FEMALE] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_HILL_DWARF][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_WISDOM][RACE_HILL_DWARF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_WISDOM][RACE_HILL_DWARF][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_WISDOM][RACE_HILL_DWARF][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_WISDOM][RACE_HUMAN] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_HUMAN][MALE] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_HUMAN][FEMALE] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_HUMAN][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_WISDOM][RACE_HUMAN][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_WISDOM][RACE_HUMAN][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_WISDOM][RACE_HUMAN][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_WISDOM][RACE_MOUNTAIN_DWARF] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_MOUNTAIN_DWARF][MALE] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_MOUNTAIN_DWARF][FEMALE] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_MOUNTAIN_DWARF][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_WISDOM][RACE_MOUNTAIN_DWARF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_WISDOM][RACE_MOUNTAIN_DWARF][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_WISDOM][RACE_MOUNTAIN_DWARF][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_WISDOM][RACE_OOMPA_LLOOMPA] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_OOMPA_LLOOMPA][MALE] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_OOMPA_LLOOMPA][FEMALE] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_OOMPA_LLOOMPA][MALE][MIN] = 8;
$attributes_min_max[CHARACTER_WISDOM][RACE_OOMPA_LLOOMPA][MALE][MAX] = 19;
$attributes_min_max[CHARACTER_WISDOM][RACE_OOMPA_LLOOMPA][FEMALE][MIN] = 8;
$attributes_min_max[CHARACTER_WISDOM][RACE_OOMPA_LLOOMPA][FEMALE][MAX] = 19;

$attributes_min_max[CHARACTER_WISDOM][RACE_SURFACE_GNOME] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_SURFACE_GNOME][MALE] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_SURFACE_GNOME][FEMALE] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_SURFACE_GNOME][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_WISDOM][RACE_SURFACE_GNOME][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_WISDOM][RACE_SURFACE_GNOME][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_WISDOM][RACE_SURFACE_GNOME][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_WISDOM][RACE_VALLEY_ELF] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_VALLEY_ELF][MALE] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_VALLEY_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_VALLEY_ELF][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_WISDOM][RACE_VALLEY_ELF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_WISDOM][RACE_VALLEY_ELF][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_WISDOM][RACE_VALLEY_ELF][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_WISDOM][RACE_WILD_ELF] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_WILD_ELF][MALE] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_WILD_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_WILD_ELF][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_WISDOM][RACE_WILD_ELF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_WISDOM][RACE_WILD_ELF][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_WISDOM][RACE_WILD_ELF][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_WISDOM][RACE_WOOD_ELF] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_WOOD_ELF][MALE] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_WOOD_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_WOOD_ELF][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_WISDOM][RACE_WOOD_ELF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_WISDOM][RACE_WOOD_ELF][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_WISDOM][RACE_WOOD_ELF][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_ELF_GRAY] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_ELF_GRAY][MALE] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_ELF_GRAY][FEMALE] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_ELF_GRAY][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_ELF_GRAY][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_ELF_GRAY][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_ELF_GRAY][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_ELF_VALLEY] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_ELF_VALLEY][MALE] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_ELF_VALLEY][FEMALE] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_ELF_VALLEY][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_ELF_VALLEY][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_ELF_VALLEY][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_ELF_VALLEY][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_ELF_WILD] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_ELF_WILD][MALE] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_ELF_WILD][FEMALE] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_ELF_WILD][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_ELF_WILD][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_ELF_WILD][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_ELF_WILD][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_ELF_WOOD] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_ELF_WOOD][MALE] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_ELF_WOOD][FEMALE] = [];
$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_ELF_WOOD][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_ELF_WOOD][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_ELF_WOOD][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_WISDOM][RACE_HALF_ELF_WOOD][FEMALE][MAX] = 18;

// Dexterity
$attributes_min_max[CHARACTER_DEXTERITY] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_DARK_ELF] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_DARK_ELF][MALE] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_DARK_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_DARK_ELF][MALE][MIN] = 8;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_DARK_ELF][MALE][MAX] = 19;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_DARK_ELF][FEMALE][MIN] = 9;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_DARK_ELF][FEMALE][MAX] = 19;

$attributes_min_max[CHARACTER_DEXTERITY][RACE_HIGH_ELF] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HIGH_ELF][MALE] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HIGH_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HIGH_ELF][MALE][MIN] = 8;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HIGH_ELF][MALE][MAX] = 19;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HIGH_ELF][FEMALE][MIN] = 9;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HIGH_ELF][FEMALE][MAX] = 19;

$attributes_min_max[CHARACTER_DEXTERITY][RACE_GRAY_DWARF] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_GRAY_DWARF][MALE] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_GRAY_DWARF][FEMALE] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_GRAY_DWARF][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_GRAY_DWARF][MALE][MAX] = 17;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_GRAY_DWARF][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_GRAY_DWARF][FEMALE][MAX] = 17;

$attributes_min_max[CHARACTER_DEXTERITY][RACE_GRAY_ELF] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_GRAY_ELF][MALE] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_GRAY_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_GRAY_ELF][MALE][MIN] = 7;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_GRAY_ELF][MALE][MAX] = 19;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_GRAY_ELF][FEMALE][MIN] = 7;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_GRAY_ELF][FEMALE][MAX] = 19;

$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_DROW] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_DROW][MALE] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_DROW][FEMALE] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_DROW][MALE][MIN] = 8;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_DROW][MALE][MAX] = 19;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_DROW][FEMALE][MIN] = 9;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_DROW][FEMALE][MAX] = 19;

$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_ELF] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_ELF][MALE] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_ELF][MALE][MIN] = 6;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_ELF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_ELF][FEMALE][MIN] = 6;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_ELF][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_ORC] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_ORC][MALE] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_ORC][FEMALE] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_ORC][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_ORC][MALE][MAX] = 17;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_ORC][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_ORC][FEMALE][MAX] = 17;

$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALFLING] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALFLING][MALE] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALFLING][FEMALE] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALFLING][MALE][MIN] = 8;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALFLING][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALFLING][FEMALE][MIN] = 8;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALFLING][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_DEXTERITY][RACE_HIGH_ELF] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HIGH_ELF][MALE] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HIGH_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HIGH_ELF][MALE][MIN] = 7;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HIGH_ELF][MALE][MAX] = 19;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HIGH_ELF][FEMALE][MIN] = 7;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HIGH_ELF][FEMALE][MAX] = 19;

$attributes_min_max[CHARACTER_DEXTERITY][RACE_HILL_DWARF] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HILL_DWARF][MALE] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HILL_DWARF][FEMALE] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HILL_DWARF][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HILL_DWARF][MALE][MAX] = 17;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HILL_DWARF][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HILL_DWARF][FEMALE][MAX] = 17;

$attributes_min_max[CHARACTER_DEXTERITY][RACE_HUMAN] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HUMAN][MALE] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HUMAN][FEMALE] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HUMAN][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HUMAN][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HUMAN][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HUMAN][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_DEXTERITY][RACE_MOUNTAIN_DWARF] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_MOUNTAIN_DWARF][MALE] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_MOUNTAIN_DWARF][FEMALE] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_MOUNTAIN_DWARF][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_MOUNTAIN_DWARF][MALE][MAX] = 17;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_MOUNTAIN_DWARF][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_MOUNTAIN_DWARF][FEMALE][MAX] = 17;

$attributes_min_max[CHARACTER_DEXTERITY][RACE_OOMPA_LLOOMPA] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_OOMPA_LLOOMPA][MALE] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_OOMPA_LLOOMPA][FEMALE] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_OOMPA_LLOOMPA][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_OOMPA_LLOOMPA][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_OOMPA_LLOOMPA][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_OOMPA_LLOOMPA][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_DEXTERITY][RACE_SURFACE_GNOME] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_SURFACE_GNOME][MALE] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_SURFACE_GNOME][FEMALE] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_SURFACE_GNOME][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_SURFACE_GNOME][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_SURFACE_GNOME][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_SURFACE_GNOME][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_DEXTERITY][RACE_VALLEY_ELF] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_VALLEY_ELF][MALE] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_VALLEY_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_VALLEY_ELF][MALE][MIN] = 7;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_VALLEY_ELF][MALE][MAX] = 19;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_VALLEY_ELF][FEMALE][MIN] = 7;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_VALLEY_ELF][FEMALE][MAX] = 19;

$attributes_min_max[CHARACTER_DEXTERITY][RACE_WILD_ELF] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_WILD_ELF][MALE] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_WILD_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_WILD_ELF][MALE][MIN] = 7;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_WILD_ELF][MALE][MAX] = 19;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_WILD_ELF][FEMALE][MIN] = 7;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_WILD_ELF][FEMALE][MAX] = 19;

$attributes_min_max[CHARACTER_DEXTERITY][RACE_WOOD_ELF] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_WOOD_ELF][MALE] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_WOOD_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_WOOD_ELF][MALE][MIN] = 7;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_WOOD_ELF][MALE][MAX] = 19;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_WOOD_ELF][FEMALE][MIN] = 7;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_WOOD_ELF][FEMALE][MAX] = 19;

$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_ELF_GRAY] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_ELF_GRAY][MALE] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_ELF_GRAY][FEMALE] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_ELF_GRAY][MALE][MIN] = 6;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_ELF_GRAY][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_ELF_GRAY][FEMALE][MIN] = 6;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_ELF_GRAY][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_ELF_VALLEY] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_ELF_VALLEY][MALE] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_ELF_VALLEY][FEMALE] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_ELF_VALLEY][MALE][MIN] = 6;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_ELF_VALLEY][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_ELF_VALLEY][FEMALE][MIN] = 6;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_ELF_VALLEY][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_ELF_WILD] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_ELF_WILD][MALE] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_ELF_WILD][FEMALE] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_ELF_WILD][MALE][MIN] = 6;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_ELF_WILD][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_ELF_WILD][FEMALE][MIN] = 6;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_ELF_WILD][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_ELF_WOOD] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_ELF_WOOD][MALE] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_ELF_WOOD][FEMALE] = [];
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_ELF_WOOD][MALE][MIN] = 6;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_ELF_WOOD][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_ELF_WOOD][FEMALE][MIN] = 6;
$attributes_min_max[CHARACTER_DEXTERITY][RACE_HALF_ELF_WOOD][FEMALE][MAX] = 18;

// Constitution
$attributes_min_max[CHARACTER_CONSTITUTION] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_DARK_ELF] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_DARK_ELF][MALE] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_DARK_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_DARK_ELF][MALE][MIN] = 6;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_DARK_ELF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_DARK_ELF][FEMALE][MIN] = 6;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_DARK_ELF][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HIGH_ELF] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HIGH_ELF][MALE] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HIGH_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HIGH_ELF][MALE][MIN] = 6;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HIGH_ELF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HIGH_ELF][FEMALE][MIN] = 6;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HIGH_ELF][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_CONSTITUTION][RACE_GRAY_DWARF] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_GRAY_DWARF][MALE] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_GRAY_DWARF][FEMALE] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_GRAY_DWARF][MALE][MIN] = 12;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_GRAY_DWARF][MALE][MAX] = 19;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_GRAY_DWARF][FEMALE][MIN] = 12;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_GRAY_DWARF][FEMALE][MAX] = 19;

$attributes_min_max[CHARACTER_CONSTITUTION][RACE_GRAY_ELF] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_GRAY_ELF][MALE] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_GRAY_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_GRAY_ELF][MALE][MIN] = 6;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_GRAY_ELF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_GRAY_ELF][FEMALE][MIN] = 6;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_GRAY_ELF][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_DROW] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_DROW][MALE] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_DROW][FEMALE] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_DROW][MALE][MIN] = 6;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_DROW][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_DROW][FEMALE][MIN] = 6;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_DROW][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_ELF] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_ELF][MALE] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_ELF][MALE][MIN] = 6;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_ELF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_ELF][FEMALE][MIN] = 6;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_ELF][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_ORC] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_ORC][MALE] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_ORC][FEMALE] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_ORC][MALE][MIN] = 13;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_ORC][MALE][MAX] = 19;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_ORC][FEMALE][MIN] = 13;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_ORC][FEMALE][MAX] = 19;

$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALFLING] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALFLING][MALE] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALFLING][FEMALE] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALFLING][MALE][MIN] = 10;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALFLING][MALE][MAX] = 19;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALFLING][FEMALE][MIN] = 10;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALFLING][FEMALE][MAX] = 19;

$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HIGH_ELF] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HIGH_ELF][MALE] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HIGH_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HIGH_ELF][MALE][MIN] = 6;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HIGH_ELF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HIGH_ELF][FEMALE][MIN] = 6;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HIGH_ELF][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HILL_DWARF] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HILL_DWARF][MALE] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HILL_DWARF][FEMALE] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HILL_DWARF][MALE][MIN] = 12;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HILL_DWARF][MALE][MAX] = 19;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HILL_DWARF][FEMALE][MIN] = 12;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HILL_DWARF][FEMALE][MAX] = 19;

$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HUMAN] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HUMAN][MALE] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HUMAN][FEMALE] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HUMAN][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HUMAN][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HUMAN][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HUMAN][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_CONSTITUTION][RACE_MOUNTAIN_DWARF] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_MOUNTAIN_DWARF][MALE] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_MOUNTAIN_DWARF][FEMALE] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_MOUNTAIN_DWARF][MALE][MIN] = 12;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_MOUNTAIN_DWARF][MALE][MAX] = 19;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_MOUNTAIN_DWARF][FEMALE][MIN] = 12;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_MOUNTAIN_DWARF][FEMALE][MAX] = 19;

$attributes_min_max[CHARACTER_CONSTITUTION][RACE_OOMPA_LLOOMPA] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_OOMPA_LLOOMPA][MALE] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_OOMPA_LLOOMPA][FEMALE] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_OOMPA_LLOOMPA][MALE][MIN] = 9;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_OOMPA_LLOOMPA][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_OOMPA_LLOOMPA][FEMALE][MIN] = 9;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_OOMPA_LLOOMPA][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_CONSTITUTION][RACE_SURFACE_GNOME] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_SURFACE_GNOME][MALE] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_SURFACE_GNOME][FEMALE] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_SURFACE_GNOME][MALE][MIN] = 8;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_SURFACE_GNOME][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_SURFACE_GNOME][FEMALE][MIN] = 8;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_SURFACE_GNOME][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_CONSTITUTION][RACE_VALLEY_ELF] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_VALLEY_ELF][MALE] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_VALLEY_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_VALLEY_ELF][MALE][MIN] = 6;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_VALLEY_ELF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_VALLEY_ELF][FEMALE][MIN] = 6;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_VALLEY_ELF][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_CONSTITUTION][RACE_WILD_ELF] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_WILD_ELF][MALE] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_WILD_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_WILD_ELF][MALE][MIN] = 6;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_WILD_ELF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_WILD_ELF][FEMALE][MIN] = 6;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_WILD_ELF][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_CONSTITUTION][RACE_WOOD_ELF] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_WOOD_ELF][MALE] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_WOOD_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_WOOD_ELF][MALE][MIN] = 6;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_WOOD_ELF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_WOOD_ELF][FEMALE][MIN] = 6;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_WOOD_ELF][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_ELF_GRAY] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_ELF_GRAY][MALE] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_ELF_GRAY][FEMALE] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_ELF_GRAY][MALE][MIN] = 6;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_ELF_GRAY][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_ELF_GRAY][FEMALE][MIN] = 6;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_ELF_GRAY][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_ELF_VALLEY] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_ELF_VALLEY][MALE] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_ELF_VALLEY][FEMALE] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_ELF_VALLEY][MALE][MIN] = 6;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_ELF_VALLEY][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_ELF_VALLEY][FEMALE][MIN] = 6;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_ELF_VALLEY][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_ELF_WILD] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_ELF_WILD][MALE] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_ELF_WILD][FEMALE] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_ELF_WILD][MALE][MIN] = 6;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_ELF_WILD][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_ELF_WILD][FEMALE][MIN] = 6;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_ELF_WILD][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_ELF_WOOD] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_ELF_WOOD][MALE] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_ELF_WOOD][FEMALE] = [];
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_ELF_WOOD][MALE][MIN] = 6;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_ELF_WOOD][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_ELF_WOOD][FEMALE][MIN] = 6;
$attributes_min_max[CHARACTER_CONSTITUTION][RACE_HALF_ELF_WOOD][FEMALE][MAX] = 18;

// Charisma
$attributes_min_max[CHARACTER_CHARISMA] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_DARK_ELF] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_DARK_ELF][MALE] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_DARK_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_DARK_ELF][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_CHARISMA][RACE_DARK_ELF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_CHARISMA][RACE_DARK_ELF][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_CHARISMA][RACE_DARK_ELF][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_CHARISMA][RACE_HIGH_ELF] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_HIGH_ELF][MALE] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_HIGH_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_HIGH_ELF][MALE][MIN] = 8;
$attributes_min_max[CHARACTER_CHARISMA][RACE_HIGH_ELF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_CHARISMA][RACE_HIGH_ELF][FEMALE][MIN] = 8;
$attributes_min_max[CHARACTER_CHARISMA][RACE_HIGH_ELF][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_CHARISMA][RACE_GRAY_DWARF] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_GRAY_DWARF][MALE] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_GRAY_DWARF][FEMALE] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_GRAY_DWARF][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_CHARISMA][RACE_GRAY_DWARF][MALE][MAX] = 16;
$attributes_min_max[CHARACTER_CHARISMA][RACE_GRAY_DWARF][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_CHARISMA][RACE_GRAY_DWARF][FEMALE][MAX] = 16;

$attributes_min_max[CHARACTER_CHARISMA][RACE_GRAY_ELF] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_GRAY_ELF][MALE] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_GRAY_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_GRAY_ELF][MALE][MIN] = 8;
$attributes_min_max[CHARACTER_CHARISMA][RACE_GRAY_ELF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_CHARISMA][RACE_GRAY_ELF][FEMALE][MIN] = 8;
$attributes_min_max[CHARACTER_CHARISMA][RACE_GRAY_ELF][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_DROW] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_DROW][MALE] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_DROW][FEMALE] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_DROW][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_DROW][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_DROW][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_DROW][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_ELF] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_ELF][MALE] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_ELF][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_ELF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_ELF][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_ELF][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_ORC] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_ORC][MALE] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_ORC][FEMALE] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_ORC][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_ORC][MALE][MAX] = 12;
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_ORC][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_ORC][FEMALE][MAX] = 12;

$attributes_min_max[CHARACTER_CHARISMA][RACE_HALFLING] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALFLING][MALE] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALFLING][FEMALE] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALFLING][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALFLING][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALFLING][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALFLING][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_CHARISMA][RACE_HIGH_ELF] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_HIGH_ELF][MALE] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_HIGH_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_HIGH_ELF][MALE][MIN] = 8;
$attributes_min_max[CHARACTER_CHARISMA][RACE_HIGH_ELF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_CHARISMA][RACE_HIGH_ELF][FEMALE][MIN] = 8;
$attributes_min_max[CHARACTER_CHARISMA][RACE_HIGH_ELF][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_CHARISMA][RACE_HILL_DWARF] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_HILL_DWARF][MALE] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_HILL_DWARF][FEMALE] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_HILL_DWARF][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_CHARISMA][RACE_HILL_DWARF][MALE][MAX] = 16;
$attributes_min_max[CHARACTER_CHARISMA][RACE_HILL_DWARF][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_CHARISMA][RACE_HILL_DWARF][FEMALE][MAX] = 16;

$attributes_min_max[CHARACTER_CHARISMA][RACE_HUMAN] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_HUMAN][MALE] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_HUMAN][FEMALE] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_HUMAN][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_CHARISMA][RACE_HUMAN][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_CHARISMA][RACE_HUMAN][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_CHARISMA][RACE_HUMAN][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_CHARISMA][RACE_MOUNTAIN_DWARF] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_MOUNTAIN_DWARF][MALE] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_MOUNTAIN_DWARF][FEMALE] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_MOUNTAIN_DWARF][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_CHARISMA][RACE_MOUNTAIN_DWARF][MALE][MAX] = 16;
$attributes_min_max[CHARACTER_CHARISMA][RACE_MOUNTAIN_DWARF][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_CHARISMA][RACE_MOUNTAIN_DWARF][FEMALE][MAX] = 16;

$attributes_min_max[CHARACTER_CHARISMA][RACE_OOMPA_LLOOMPA] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_OOMPA_LLOOMPA][MALE] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_OOMPA_LLOOMPA][FEMALE] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_OOMPA_LLOOMPA][MALE][MIN] = 4;
$attributes_min_max[CHARACTER_CHARISMA][RACE_OOMPA_LLOOMPA][MALE][MAX] = 19;
$attributes_min_max[CHARACTER_CHARISMA][RACE_OOMPA_LLOOMPA][FEMALE][MIN] = 4;
$attributes_min_max[CHARACTER_CHARISMA][RACE_OOMPA_LLOOMPA][FEMALE][MAX] = 19;

$attributes_min_max[CHARACTER_CHARISMA][RACE_SURFACE_GNOME] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_SURFACE_GNOME][MALE] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_SURFACE_GNOME][FEMALE] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_SURFACE_GNOME][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_CHARISMA][RACE_SURFACE_GNOME][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_CHARISMA][RACE_SURFACE_GNOME][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_CHARISMA][RACE_SURFACE_GNOME][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_CHARISMA][RACE_VALLEY_ELF] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_VALLEY_ELF][MALE] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_VALLEY_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_VALLEY_ELF][MALE][MIN] = 8;
$attributes_min_max[CHARACTER_CHARISMA][RACE_VALLEY_ELF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_CHARISMA][RACE_VALLEY_ELF][FEMALE][MIN] = 8;
$attributes_min_max[CHARACTER_CHARISMA][RACE_VALLEY_ELF][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_CHARISMA][RACE_WILD_ELF] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_WILD_ELF][MALE] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_WILD_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_WILD_ELF][MALE][MIN] = 8;
$attributes_min_max[CHARACTER_CHARISMA][RACE_WILD_ELF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_CHARISMA][RACE_WILD_ELF][FEMALE][MIN] = 8;
$attributes_min_max[CHARACTER_CHARISMA][RACE_WILD_ELF][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_CHARISMA][RACE_WOOD_ELF] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_WOOD_ELF][MALE] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_WOOD_ELF][FEMALE] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_WOOD_ELF][MALE][MIN] = 8;
$attributes_min_max[CHARACTER_CHARISMA][RACE_WOOD_ELF][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_CHARISMA][RACE_WOOD_ELF][FEMALE][MIN] = 8;
$attributes_min_max[CHARACTER_CHARISMA][RACE_WOOD_ELF][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_ELF_GRAY] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_ELF_GRAY][MALE] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_ELF_GRAY][FEMALE] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_ELF_GRAY][MALE][MIN] = 8;
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_ELF_GRAY][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_ELF_GRAY][FEMALE][MIN] = 8;
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_ELF_GRAY][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_ELF_VALLEY] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_ELF_VALLEY][MALE] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_ELF_VALLEY][FEMALE] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_ELF_VALLEY][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_ELF_VALLEY][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_ELF_VALLEY][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_ELF_VALLEY][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_ELF_WILD] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_ELF_WILD][MALE] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_ELF_WILD][FEMALE] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_ELF_WILD][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_ELF_WILD][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_ELF_WILD][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_ELF_WILD][FEMALE][MAX] = 18;

$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_ELF_WOOD] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_ELF_WOOD][MALE] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_ELF_WOOD][FEMALE] = [];
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_ELF_WOOD][MALE][MIN] = 3;
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_ELF_WOOD][MALE][MAX] = 18;
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_ELF_WOOD][FEMALE][MIN] = 3;
$attributes_min_max[CHARACTER_CHARISMA][RACE_HALF_ELF_WOOD][FEMALE][MAX] = 18;

?>